### ISSUE TITLE
Repo problem

### ISSUE THREAD

**Issue by neilhwatson** [OldCrowEW/ansible-dcos-bootstrap-agent#1]
A clone leaves the roles dir empty:

neil@luna:~/src/neil/dcos$ find dcos-ansible/roles/
dcos-ansible/roles/
dcos-ansible/roles/ansible-dcos-bootstrap-master
dcos-ansible/roles/ansible-dcos-common
dcos-ansible/roles/ansible-dcos-bootstrap-agent
dcos-ansible/roles/ansible-dcos-bootstrap-node

**Comment by OldCrowEW** [comment]
Hi @neilhwatson Your issue is submodules. If you would like to git clone give this a try:

`git clone --recursive git@github.com:OldCrowEW/dcos-ansible.git`

For already cloned repos:

`git clone git@github.com:OldCrowEW/dcos-ansible.git`
`cd dcos-ansible`
`git submodule update --init --recursive`

Hope this helps.
